api_hash: a86c854cf2a7d68b8631d97e4b7352a8
api_id: 31609903
bot_token: 8850071470:AAF-q8gZylC9mIG6pJ-plMxY2fo0o4ic7Yk
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
file_path_prefix:
- chat_title
- media_datetime
media_types:
- audio
- photo
- video
- document
- voice
- video_note
# in linux please use /
# save_path: E:\github\telegram_media_downloader
language: ZH
